export const ROUTES = {
  home: "/",
  join: "/join",
  signIn: "/sign-in",
  signUp: "/sign-up/1",
  signUpStep2:"/sign-up/2",
  forgotPassword:"/forgot-password",
  faq: "/faq",
  explore: "/explore",
  nftProject: "/nft/[projectId]",
  project:"/nft/project",
  artistProfile: "/artist/",
  payment: "/payment",
  moonpay: "/moonpay",
  account: "/my-account",
  checkout: "/checkout",
  transactionSuccess: "/transaction/success",
  transactionFailure: "/transaction/failure",
  projectRegister: "/project/register",
  projectWaiting: "/project/waiting/[projectId]",
};
